"""initial schema

Revision ID: 27cc3f480820
Revises: 
Create Date: 2026-09-28 12:42:37.298397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27cc3f480820'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addons',
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.Column('addon_name', sa.String(length=50), nullable=False),
    sa.Column('price_rule', sa.String(length=50), nullable=False),
    sa.Column('applicability_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('addon_id'),
    sa.UniqueConstraint('addon_name')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('depreciation_slabs',
    sa.Column('slab_id', sa.Integer(), nullable=False),
    sa.Column('age_min_months', sa.Integer(), nullable=False),
    sa.Column('age_max_months', sa.Integer(), nullable=False),
    sa.Column('depreciation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('age_min_months <= age_max_months', name='ck_depreciation_band_order'),
    sa.PrimaryKeyConstraint('slab_id'),
    sa.UniqueConstraint('age_min_months', 'age_max_months', name='uq_depreciation_age_band')
    )
    op.create_table('ncb_slabs',
    sa.Column('slab_id', sa.Integer(), nullable=False),
    sa.Column('claim_free_years', sa.Integer(), nullable=False),
    sa.Column('ncb_discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('slab_id'),
    sa.UniqueConstraint('claim_free_years')
    )
    op.create_table('rate_card',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('city_zone', sa.String(length=50), nullable=False),
    sa.Column('cc_band', sa.String(length=20), nullable=False),
    sa.Column('od_rate_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tp_premium_flat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('rate_id'),
    sa.UniqueConstraint('city_zone', 'cc_band', name='uq_rate_card_zone_band')
    )
    op.create_table('vehicle_master',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('engine_cc', sa.Integer(), nullable=False),
    sa.Column('ex_showroom_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("fuel_type IN ('petrol', 'diesel', 'electric', 'cng')", name='ck_vehicle_fuel_type'),
    sa.CheckConstraint('engine_cc >= 0', name='ck_vehicle_engine_cc'),
    sa.CheckConstraint('ex_showroom_price > 0', name='ck_vehicle_price'),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('make', 'model', 'year', 'fuel_type', name='uq_vehicle_make_model_year_fuel')
    )
    op.create_table('quotes',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('claim_free_years', sa.Integer(), nullable=False),
    sa.Column('idv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('od_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ncb_discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tp_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('addons_selected', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('total_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('calculation_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan_tier IN ('basic', 'standard', 'premium')", name='ck_quotes_plan_tier'),
    sa.CheckConstraint("status IN ('draft', 'sent', 'converted')", name='ck_quotes_status'),
    sa.CheckConstraint('claim_free_years >= 0', name='ck_quotes_claim_free_years'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_master.vehicle_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_index('ix_quotes_customer_id', 'quotes', ['customer_id'], unique=False)
    op.create_index('ix_quotes_status', 'quotes', ['status'], unique=False)
    op.create_index('ix_quotes_vehicle_id', 'quotes', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_vehicle_id', table_name='quotes')
    op.drop_index('ix_quotes_status', table_name='quotes')
    op.drop_index('ix_quotes_customer_id', table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('vehicle_master')
    op.drop_table('rate_card')
    op.drop_table('ncb_slabs')
    op.drop_table('depreciation_slabs')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('addons')
    # ### end Alembic commands ###
